[pytest]
testpaths = test
python_files = *test*.py
python_classes = *Test*
python_functions = *test*
addopts = --alluredir=allure-results --clean-alluredir
markers =
    ui: Custom marker for web browser interface regression automation tests (Selenium)
    api: Custom marker for backend microservice integration validation tests (Requests)